name: Test Server

on:
  pull_request:

defaults:
  run:
    working-directory: Server/RiversideServer

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Swift
        uses: SwiftyLab/setup-swift@latest
        with:
          development: true

      - name: Build
        run: swift build

      - name: Run tests
        run: swift test

